# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: macOS-latest

steps:
#- script: brew install podman
#  displayName: 'install podman'

- script: rustup target add arm-unknown-linux-gnueabihf
  displayName: 'Add rustup target'

#- script: cargo install cross
#  displayName: 'cargo install cross'

- script: brew tap messense/macos-cross-toolchains && brew install arm-unknown-linux-gnueabihf
  displayName: 'Add linker'

- script: cargo build --target arm-unknown-linux-gnueabihf
  displayName: 'cargo cross build'
