# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: macOS-latest

steps:
- script: rustup target add arm-unknown-linux-gnueabihf
  displayName: 'Add rustup target'

- script: cargo install cross
  displayName: 'cargo install cross'

- script: cargo build --target arm-unknown-linux-gnueabihf
  displayName: 'cargo build'
