# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: macOS-latest

steps:
#- script: brew install podman
#  displayName: 'install podman'

- script: rustup target add arm-unknown-linux-gnueabihf
  displayName: 'Add rustup target'

#- script: cargo install cross
#  displayName: 'cargo install cross'

- script: brew tap messense/macos-cross-toolchains && brew install arm-unknown-linux-gnueabihf
  displayName: 'Add linker'


- script: |
    curl -L 'https://gstreamer.freedesktop.org/data/pkg/osx/1.20.4/gstreamer-1.0-devel-1.20.4-universal.pkg' -o "$(pwd)/gstreamer-devel.pkg"
    sudo installer -verbose -pkg "$(pwd)/gstreamer-devel.pkg" -target /
    PKG_CONFIG_PATH="/Library/Frameworks/GStreamer.framework/Versions/1.0/lib/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}"
    PKG_CONFIG_GSTREAMER_1_0_PREFIX="/Library/Frameworks/GStreamer.framework/Versions/1.0"
    echo "##vso[task.setvariable variable=PKG_CONFIG_PATH]${PKG_CONFIG_PATH}"
    echo "##vso[task.setvariable variable=PKG_CONFIG_GSTREAMER_1_0_PREFIX]${PKG_CONFIG_GSTREAMER_1_0_PREFIX}"
    echo "##vso[task.setvariable variable=PKG_CONFIG_PATH]${PKG_CONFIG_PATH}"
    brew install pkg-config
  displayName: 'Install Gstreamer on macOS'

- script: |
    echo "PATH=${PATH}"
    echo "GSTREAMER_1_0_ROOT_MSVC_X86_64=${GSTREAMER_1_0_ROOT_MSVC_X86_64}"
    echo "PKG_CONFIG_PATH=${PKG_CONFIG_PATH}"
    cargo build --target arm-unknown-linux-gnueabihf
  displayName: 'cargo cross build'
